pipeline {
agent { label 'agent' }

options{
    timeout(time: 30, unit: 'MINUTES')
    disableConcurrentBuilds()
    //retry(1)
}

environment {
    AWS_REGION = 'us-east-1'
    ACCOUNT_ID = '222634367824'
    IMAGE_TAG = "${BUILD_NUMBER}"
    ECR_REPO = 'expense/dev/backend'
}

stages {

    stage('Checkout Code') {
        steps {
            git branch: 'main', url: 'https://github.com/Vamsi987dev/docker-containerization.git'
        }
    }

    stage('Build Docker Image') {
        steps {
            sh '''
            docker build -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG ./expense/backend
            '''
        }
    }

    stage('Login to ECR') {
        steps {
            sh '''
            aws ecr get-login-password --region $AWS_REGION | \
            docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
            '''
        }
    }

    stage('Push Image to ECR') {
        steps {
            sh '''
            docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
            '''
        }
    }

}

post {
    success {
        echo "Docker image built and pushed successfully!"
    }

    failure {
        echo "Pipeline failed. Check logs."
    }
}

}
